USER_PROFILES_JWT_PUBLIC_KEY: app-local.pub

MYSQL_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root
LOG_TO_FILE: false

spring:
  cloud.gcp.sql.enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/catalog
    username: ${MYSQL_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3308/catalog

#From Gateway configs
FRONTEND_URL: http://localhost:3000
#From Gateway configs

#User Profiles
MONGO_SERVER_URL: localhost
MONGO_SERVER_PORT: 28017
MONGO_USERNAME: root
MONGO_PASSWORD: root1
#User Profiles

#Search
ELASTICSEARCH_SERVER_URL: localhost:9200
#Search